### ISSUE TITLE
[WiiU] Does not build for WiiU

### ISSUE THREAD

**Issue by Ploggy** [nbarkhina/numero#4]
Hi, I just tried to build this Core for WiiU but it shows this error?

![image](https://user-images.githubusercontent.com/1160255/212574425-66544682-8d08-44f3-afd7-c40f1eb14667.png)

**Comment by nbarkhina** [comment]
just pushed a fix for WiiU, please try it again

**Comment by Ploggy** [comment]
Awesome, it compiles fine now :)
