### ISSUE TITLE
Permission to add numero to Steam as free DLC for RetroArch

### ISSUE THREAD

**Issue by fpscan** [nbarkhina/numero#6]
Hi there, we would like to seek your permission to include numero as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide. You can reach me on discord as well, which my handle is gadsby#7998

**Comment by nbarkhina** [comment]
Hi @fpscan are you asking about Numero or ep128emu? If it's for Numero then yes you have my permission :)

**Comment by fpscan** [comment]
> Hi @fpscan are you asking about Numero or ep128emu? If it's for Numero then yes you have my permission :)

Ah, sorry, it is poorly copy pasted text, I just changed and yeah I meant to Numero which I think people will find it very interesting... While ep128emu mentioned, you can see the page so you can guess how it will look: https://store.steampowered.com/app/2234340/RetroArch__ep128emu/ if you have any request to show in the page let me know! I can use your real name or github handle as a dev in the steam page etc.
