### ISSUE TITLE
Libretro buildbot CI

### ISSUE THREAD

**Issue by LibretroAdmin** [nbarkhina/numero#7]
Hi there, we finally added this to our buildbot CI - you can see the current pipeline results here -

https://git.libretro.com/libretro/numero/-/pipelines/172715

A couple of the platforms don't build, hopefully it can be fixed.

**Comment by nbarkhina** [comment]
Wow Thank you so much!! I will look into the failing platforms and see if I can get them fixed.

Thanks again!

**Comment by LibretroAdmin** [comment]
No problem, the pleasure is all ours. Thanks for creating the core.

**Comment by LibretroAdmin** [comment]
Good news, the targets all build now!

https://git.libretro.com/libretro/numero/-/pipelines/172992

Thanks for the effort!

**Comment by LibretroAdmin** [comment]
@fpscan will be preparing the Steam core DLC soon.
